import test from 'node:test';
import assert from 'node:assert/strict';
import {promises as fs} from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {LocalBackend} from '../backend.mjs';
import {LivePreview,validateInput} from '../live.mjs';
import {serve} from '../server.mjs';
const a='11111111-1111-1111-1111-111111111111',b='22222222-2222-2222-2222-222222222222';
async function root(t){const p=await fs.mkdtemp(path.join(os.tmpdir(),'studio-backend-'));t.after(()=>fs.rm(p,{recursive:true,force:true}));return p;}
test('backend credentials are private, stable, and project scoped',async t=>{const r=await root(t),s=new LocalBackend(r),key=await s.key(a);assert.equal(key.length,64);assert.equal(await new LocalBackend(r).key(a),key);assert.equal((await fs.stat(path.join(r,a,'backend/key'))).mode&0o777,0o600);assert.equal(await s.authorized(a,key),true);assert.equal(await s.authorized(b,key),false);assert.equal(await s.authorized(a,''),false);});
test('backend persists concurrent writes and isolates test and preview records',async t=>{const r=await root(t),s=new LocalBackend(r);await Promise.all(Array.from({length:20},(_,i)=>s.mutate(a,'preview','note-'+i,{title:'Note '+i})));assert.equal((await new LocalBackend(r).records(a,'preview')).length,20);assert.deepEqual(await s.records(a,'test-1'),[]);await s.mutate(a,'preview','note-1',null);assert.equal((await s.records(a,'preview')).length,19);assert.deepEqual(await s.records(b,'preview'),[]);});
test('backend rejects traversal and malformed or oversized fields',async t=>{const s=new LocalBackend(await root(t));assert.throws(()=>s.dir('../secrets'));for(const [ns,id,fields] of [['../x','a',{}],['preview','../x',{}],['preview','a',{title:4}],['preview','a',{title:'x'.repeat(4001)}],['preview','a',[]]])await assert.rejects(s.mutate(a,ns,id,fields));});
test('HTTP backend requires project authorization and blocks cross-origin requests',async t=>{const app=await serve({root:await root(t),port:0});t.after(()=>new Promise(r=>app.server.close(r)));const p=await app.studio.create('Notes','Notes','codex','custom','local');const key=await app.studio.backend.key(p.id),url=app.origin+'/backend/'+p.id+'/records';assert.equal((await fetch(url)).status,403);const headers={Authorization:'Bearer '+key,'X-Workspace':'preview','Content-Type':'application/json'};assert.equal((await fetch(url,{headers:{...headers,Origin:'https://untrusted.example'}})).status,403);assert.equal((await fetch(url+'/note-1',{method:'PUT',headers,body:JSON.stringify({fields:{title:'Test'}})})).status,200);assert.equal((await(await fetch(url,{headers})).json())[0].fields.title,'Test');assert.deepEqual(await(await fetch(url,{headers:{...headers,'X-Workspace':'test-1'}})).json(),[]);assert.equal((await fetch(url+'/note-1',{method:'DELETE',headers})).status,204);assert.deepEqual(await(await fetch(url,{headers})).json(),[]);});
test('live commands accept only bounded normalized input',()=>{assert.deepEqual(validateInput({action:'tap',x:0.2,y:1,ignored:'x'}),{action:'tap',x:0.2,y:1});for(const c of [{action:'shell'},{action:'tap',x:NaN,y:0},{action:'swipe',x:0,y:0,endX:2,endY:0},{action:'type',text:''},{action:'type',text:'x'.repeat(501)}])assert.throws(()=>validateInput(c));});
test('live preview fails closed for stale evidence and releases reservation',async()=>{const studio={jobs:new Map(),reserved:false,get:async()=>({template:'custom',evidence:{sourceHash:'old'}}),fingerprint:async()=>'new'};const live=new LivePreview(studio);await assert.rejects(live.start(a),/Run app checks/);assert.equal(studio.reserved,false);assert.equal(live.status().state,'stopped');studio.reserved=true;await assert.rejects(live.start(a),/active task/);});
test('live queue is bounded, scoped, authenticated, and never exposes its key',()=>{const live=new LivePreview({});live.session={id:'session',key:'secret',project:a,state:'ready',queue:[],next:0,completed:0,frameNumber:0};assert.equal(live.authorize('session','secret'),true);assert.equal(live.authorize('session','wrong'),false);assert.throws(()=>live.input(b,{action:'relaunch'}));for(let i=0;i<8;i++)live.input(a,{action:'relaunch'});assert.throws(()=>live.input(a,{action:'relaunch'}),/queued/);assert.equal(live.command().id,1);assert.equal(JSON.stringify(live.status()).includes('secret'),false);assert.throws(()=>live.frame(Buffer.from('not png'),0));live.session.stopping=true;assert.deepEqual(live.command(),{action:'stop'});});
test('recoverable input errors are exposed without accepting arbitrary driver text',()=>{const live=new LivePreview({});live.session={state:'ready',frameNumber:0};const png=Buffer.from([137,80,78,71,13,10,26,10]);live.frame(png,1,'Tap a text field in the simulator before sending text.');assert.match(live.status().inputError,/Tap a text field/);assert.equal(live.status().state,'ready');live.frame(png,2,'untrusted diagnostics');assert.equal(live.status().inputError,null);});
