import { z } from 'zod';
import { fromLCH,toLCH,scale,contrast,legible,onColor } from './math.js';
export const FAMILIES=['Neutral / Minimal','Blue','Indigo','Violet','Purple','Magenta','Teal','Cyan','Green','Emerald','Mint','Yellow','Amber','Orange','Red','Rose','Pink','Brown / Earth','Navy / Midnight','Slate / Graphite','Pastel','Muted','High Contrast','Monochrome','Gradient-led','Dark OLED','Warm Light','Cool Light','Glass / Translucent','Dynamic Brand','Category-aware palettes'] as const;
export const STRATEGIES=['monochromatic','analogous','complementary','split-complementary','triadic','neutral-plus-accent','dominant-plus-supporting','restrained gradient'] as const;
export const TOKENS=['primary','primaryPressed','primaryDisabled','primaryContainer','onPrimary','secondary','secondaryContainer','onSecondary','tertiary','accent','background','backgroundSecondary','surface','surfaceElevated','surfaceGrouped','surfaceOverlay','border','separator','textPrimary','textSecondary','textTertiary','textDisabled','iconPrimary','iconSecondary','success','successContainer','warning','warningContainer','error','errorContainer','info','selection','focus','link','destructive'] as const;
export type Palette=Record<typeof TOKENS[number],string>;
const color=z.string().regex(/^#[\da-fA-F]{6}$/);
export const generationSchema=z.object({description:z.string().max(2000).default(''),category:z.string().max(80).default(''),mood:z.array(z.string().max(40)).max(16).default([]),primaryColor:color.optional(),brandColors:z.array(color).max(32).default([]),existingColors:z.array(color).max(128).default([]),existingTokens:z.record(color).refine(v=>Object.keys(v).length<=128,'At most 128 tokens').default({}),family:z.enum(FAMILIES).optional(),strategy:z.enum(STRATEGIES).default('dominant-plus-supporting'),appearance:z.enum(['both','light','dark','oled']).default('both'),accessibility:z.enum(['standard','high']).default('standard'),imageSamples:z.array(z.object({color,weight:z.number().positive().max(1e6).default(1)}).strict()).max(4096).default([])}).strict();
export type GenerationInput=z.input<typeof generationSchema>;
const HUES=[0,250,275,295,310,335,185,210,145,160,165,100,80,50,27,12,355,60,260,250];
const hash=(s:string)=>Array.from(s).reduce((a,c)=>(Math.imul(a,31)+c.charCodeAt(0))>>>0,0);
/** Samples must be supplied by a local image decoder, never fetched by this tool. */
export function extractSeed(samples:{color:string;weight:number}[]) {
 const buckets=new Map<string,number>();
 for(const s of samples){const [L,C]=toLCH(s.color);if(L<.08||L>.96||C<.025)continue;const key=s.color.toUpperCase();buckets.set(key,(buckets.get(key)||0)+s.weight);}
 const ranked=[...buckets].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));
 return {seed:ranked[0]?.[0],candidates:ranked.slice(0,8).map(([color,weight])=>({color,weight,whiteTextContrast:contrast(color,'#FFFFFF'),blackTextContrast:contrast(color,'#000000')})),note:'Extracted candidate, not an official brand color. Opaque sampled pixels only; transparent/background pixels must be removed by the decoder.'};
}
export function inspectContrast(p:Palette,minimum=4.5){
 const pairs:[string,keyof Palette,keyof Palette,number|null][]=[['primary text','textPrimary','background',minimum],['secondary text','textSecondary','background',minimum],['surface text','textPrimary','surface',minimum],['elevated text','textPrimary','surfaceElevated',minimum],['grouped text','textSecondary','surfaceGrouped',minimum],['primary button','onPrimary','primary',minimum],['pressed button','onPrimary','primaryPressed',minimum],['secondary button','onSecondary','secondary',minimum],['destructive label','destructive','background',minimum],['link','link','background',minimum],['selected text','textPrimary','selection',minimum],['success label','success','successContainer',minimum],['warning label','warning','warningContainer',minimum],['error label','error','errorContainer',minimum],['focus','focus','background',3],['disabled control','textDisabled','primaryDisabled',null]];
 return pairs.map(([name,foreground,background,required])=>({name,foreground,background,ratio:contrast(p[foreground],p[background]),required,status:required===null?'informational':contrast(p[foreground],p[background])>=required?'pass':'fail'}));
}
export function generateColorSystem(input:GenerationInput={}) {
 const o=generationSchema.parse(input),intent=[o.description,o.category,...o.mood].join(' ').toLowerCase(),n=hash(intent),extraction=extractSeed(o.imageSamples);
 const inferred=FAMILIES.find(f=>f.length>3&&intent.includes(f.toLowerCase())) || (/calm|trust|finance|bank|professional|security|enterprise/.test(intent)?'Blue':/health|fitness|travel|food/.test(intent)?'Teal':/playful|social|music|gaming|dating/.test(intent)?'Violet':'Neutral / Minimal');
 const family=o.family||inferred,idx=FAMILIES.indexOf(family),hue=HUES[idx]??(n%360);
 const explicit=o.primaryColor||o.brandColors[0]||o.existingTokens.primary||o.existingTokens.Primary||o.existingColors[0]||extraction.seed;
 const neutral=['Neutral / Minimal','Slate / Graphite','Monochrome'].includes(family);
 const soft=/soft|calm|muted|editorial|focused|serious|premium|luxurious/.test(intent)||['Pastel','Muted','Brown / Earth'].includes(family);
 const seed=explicit||fromLCH(.58,neutral?.025:soft?.10:.16,(hue+(o.family?0:n%19-9)+360)%360);
 const [,seedC,H]=toLCH(seed),C=Math.min(seedC,soft?.12:.19),strategy=family==='Monochrome'?'monochromatic':family==='Gradient-led'&&input.strategy===undefined?'restrained gradient':o.strategy;
 const shift=({'monochromatic':0,'analogous':25,'complementary':180,'split-complementary':150,'triadic':120,'neutral-plus-accent':0,'dominant-plus-supporting':35,'restrained gradient':20})[strategy];
 const secondary=fromLCH(.6,strategy==='neutral-plus-accent'?.025:C*.75,H+shift),accent=fromLCH(.62,C*.9,H+(strategy==='triadic'?240:shift+15));
 function appearance(dark:boolean,high:boolean):Palette {
  const min=high?7:4.5,baseH=family==='Warm Light'?65:family==='Cool Light'?250:H;
  const c=(l:number,ch=.012,h=baseH)=>fromLCH(l,ch,h);
  const background=dark?(o.appearance==='oled'||family==='Dark OLED'?'#000000':c(.15)):c(.985),surface=dark?c(.20):'#FFFFFF',surfaceElevated=dark?c(.25):c(.96),surfaceGrouped=dark?c(.18):c(.95),selection=dark?c(.31,.055):c(.90,.035);
  const backgrounds=[background,surface,surfaceElevated,surfaceGrouped,selection];
  const primary=legible(c(dark?.73:.48,C,H),[background],3),onPrimary=onColor(primary);
  const button=legible(primary,[onPrimary],min),secondaryValue=legible(c(dark?.74:.48,C*.75,toLCH(secondary)[2]),[onColor(c(dark?.74:.48,C*.75,toLCH(secondary)[2]))],min);
  const status=(h:number)=>{const container=c(dark?.25:.95,.035,h);return [legible(c(dark?.78:.42,.15,h),[container,background],min),container];};
  const [success,successContainer]=status(150),[warning,warningContainer]=status(80),[error,errorContainer]=status(27);
  const textPrimary=legible(c(dark?.96:.18,.006),backgrounds,min),textSecondary=legible(c(dark?.78:.38,.008),backgrounds,min);
  return {primary:button,primaryPressed:legible(c(dark?.67:.40,C,H),[onPrimary],min),primaryDisabled:c(dark?.32:.88,.016),primaryContainer:c(dark?.28:.94,.045,H),onPrimary,secondary:secondaryValue,secondaryContainer:c(dark?.27:.94,.035,H+shift),onSecondary:onColor(secondaryValue),tertiary:c(dark?.78:.46,C*.6,H+shift+15),accent:legible(accent,[background],3),background,backgroundSecondary:surfaceGrouped,surface,surfaceElevated,surfaceGrouped,surfaceOverlay:surfaceElevated,border:c(dark?.50:.66,.008),separator:c(dark?.36:.84,.005),textPrimary,textSecondary,textTertiary:legible(c(dark?.7:.45,.008),backgrounds,min),textDisabled:c(dark?.62:.50,.004),iconPrimary:textPrimary,iconSecondary:textSecondary,success,successContainer,warning,warningContainer,error,errorContainer,info:legible(c(dark?.78:.43,.12,250),[background],min),selection,focus:legible(button,[background],3),link:legible(button,[background],min),destructive:error};
 }
 const light=appearance(false,(o.accessibility==='high'||family==='High Contrast')),dark=appearance(true,(o.accessibility==='high'||family==='High Contrast')),highContrastLight=appearance(false,true),highContrastDark=appearance(true,true);
 const variants={light,dark,highContrastLight,highContrastDark};
 const assetName=(k:string)=>k[0].toUpperCase()+k.slice(1);
 const assetTokens={version:1,colors:Object.fromEntries([...TOKENS.map(k=>[assetName(k),Object.fromEntries(Object.entries(variants).map(([a,p])=>[a,p[k]]))]),['AccentColor',Object.fromEntries(Object.entries(variants).map(([a,p])=>[a,p.primary]))]])};
 const gradients=Object.fromEntries(Object.entries({light,dark}).map(([name,p])=>{const [L,c,h]=toLCH(p.primary);const stops=Array.from({length:5},(_,i)=>fromLCH(L,c*.8,h+i*4));const foreground=onColor(stops[0]);return [name,{stops,foreground,contrast:stops.map(s=>contrast(foreground,s)),verification:'Stop samples only; rendered interpolation and overlays require inspection. Decorative use by default.'}];}));
 return {version:1,family,strategy,seed,seedSource:explicit?'provided color or extracted candidate':'intent heuristic',preferredAppearance:o.appearance,rationale:[`Derived ${family} from ${explicit?'supplied color evidence':'category, description and mood heuristics'}; category is a starting suggestion, not a rule.`,`${strategy} limits supporting hue variation; gamut mapping reduces chroma at constant lightness/hue.`, 'Dark surfaces and foregrounds are generated independently; brand seed is preserved separately from contrast-adjusted UI colors.'],semanticTokens:TOKENS,light,dark,highContrastLight,highContrastDark,tonalScales:{primary:scale(seed),secondary:scale(secondary),accent:scale(accent)},contrast:Object.fromEntries(Object.entries(variants).map(([a,p])=>[a,inspectContrast(p,a.startsWith('high')||(o.accessibility==='high'||family==='High Contrast')?7:4.5)])),gradients,assetTokens,extraction,implementation:{swiftUI:'import SwiftUI\nenum AppColors {\n'+TOKENS.map(k=>`    static let ${k} = Color("${assetName(k)}")`).join('\n')+'\n}\n// Text("Continue").foregroundStyle(AppColors.onPrimary).padding().background(AppColors.primary)',uiKit:'import UIKit\nenum AppUIColors {\n'+TOKENS.map(k=>`    static var ${k}: UIColor { UIColor(named: "${assetName(k)}") ?? .label }`).join('\n')+'\n}'},guidance:['Prefer system label/link/grouped-background colors where branding is unnecessary. These custom tokens are optional, not replacements for system semantics.','Use tint for native controls, destructive Button roles, hierarchical SF Symbols and system materials. Glass is an opaque fallback recommendation, not simulated Liquid Glass.','Test Increase Contrast, Differentiate Without Color, Dynamic Type, semantic labels and non-color state indicators. Contrast alone is not full accessibility.','Existing tokens supply a seed, not a lossless migration. Review the preview and use the existing assets CLI only after explicit permission.','Only opaque sRGB is generated. No HDR, Display P3, alpha compositing or alpha compositing.']};
}
