import {McpServer} from '@modelcontextprotocol/sdk/server/mcp.js';
import {z} from 'zod';
import {templates,getTemplate,profiles,profileSource} from './catalog.js';
import {recipeSchema,generateSet,inspectSet,previewSet,exportSet,localizeSet} from './studio.js';
export function registerScreenshotTools(server:McpServer){
 const result=async(work:()=>unknown|Promise<unknown>)=>{try{return {content:[{type:'text' as const,text:JSON.stringify(await work(),null,2)}]};}catch(e){return {isError:true,content:[{type:'text' as const,text:e instanceof Error?e.message:String(e)}]};}};
 const ro={readOnlyHint:true,destructiveHint:false,openWorldHint:false},write={...ro,readOnlyHint:false};
 const directory=z.string().min(1).max(4096);
 server.registerTool('list_screenshot_templates',{description:'Use this before creating local App Store screenshot sets. List structurally distinct layouts and dated output profiles. No network, capture, upload or Apple approval.',inputSchema:{},annotations:ro},async()=>result(()=>({templates,profiles,profileSource})));
 server.registerTool('get_screenshot_template',{description:'Use this to choose a Screenshot Studio layout. Inspect text positions, device placement, background, callouts and safe-region requirements before rendering.',inputSchema:{template:z.string()},annotations:ro},async({template})=>result(()=>getTemplate(template)));
 for(const name of ['generate_screenshot_set','generate_screenshot_variants','render_app_store_screenshot'] as const){server.registerTool(name,{description:'Use this to render supplied PNG/JPEG captures offline into NEW local directories with neutral frames, supplied copy, hashed metadata and a gallery. Does not capture or upload. Single-image tool requires one screen and template; variants requires multiple templates.',inputSchema:{recipe:recipeSchema},annotations:write},async({recipe})=>result(()=>{if(name==='render_app_store_screenshot'&&(recipe.screens?.length!==1||recipe.templates.length!==1))throw Error('Single rendering requires one screen and one template.');if(name==='generate_screenshot_variants'&&recipe.templates.length<2)throw Error('Supply at least two templates.');return generateSet(recipe);}));}
 server.registerTool('inspect_screenshot_set',{description:'Use this before sharing/exporting a local screenshot set. Verify dimensions, RGB PNG format, hashes, recorded bounds, text contrast and duplicate sources. This is not Apple approval or a complete design review.',inputSchema:{directory},annotations:ro},async({directory})=>result(()=>inspectSet(directory)));
 server.registerTool('preview_screenshot_set',{description:'Use this to locate the generated local contact sheet and HTML gallery after validating a screenshot set. Returns local paths only; does not open a browser or upload.',inputSchema:{directory},annotations:ro},async({directory})=>result(()=>previewSet(directory)));
 server.registerTool('export_screenshot_set',{description:'Use this after visually reviewing a local set. Copy validated PNG files and export metadata to a NEW directory, refusing invalid or modified outputs. No upload or automatic App Store submission.',inputSchema:{directory,outputDirectory:directory},annotations:write},async({directory,outputDirectory})=>result(()=>exportSet(directory,outputDirectory)));
 server.registerTool('localize_screenshot_set',{description:'Use this to render a new locale from supplied translated copy, preserving screen order and templates. No hosted translation. Font coverage and overflow must pass; existing sets are never overwritten.',inputSchema:{directory,outputDirectory:directory,locale:z.string(),copy:z.array(z.object({headline:z.string().min(1).max(240),subtitle:z.string().max(240).optional(),badge:z.string().max(240).optional()}).strict()).min(1).max(10),fontPaths:z.array(directory).min(1).max(8).optional()},annotations:write},async({directory,outputDirectory,locale,copy,fontPaths})=>result(()=>localizeSet(directory,locale,copy,outputDirectory,fontPaths)));
}
