/** Single source for MCP guidance and the generated integrations website. */
export interface Integration {
  id: string; name: string; frameworks: string[]; minimumIOS: number;
  operations: string[]; permissions: string[]; capabilities: string[];
  approach: string; limitations: string[]; verification: string[]; guides: string[];
  appleURL: string; template: string;
}
const common = ['Test cancellation and denied/restricted access without losing app state.', 'Build the selected app target; verify the actual user flow on a device.'];
function entry(id: string, name: string, frameworks: string[], operations: string[], permissions: string[], approach: string, limitations: string[], guides: string[], template: string): Integration {
  return {id,name,frameworks,minimumIOS:17,operations,permissions,capabilities:[],approach,limitations,verification:common,guides,template,appleURL:`https://developer.apple.com/documentation/${frameworks[0]!.toLowerCase()}`};
}
export const integrations: readonly Integration[] = [
 entry('calendar','Calendar',['EventKit','EventKitUI'],['authorize','calendars','fetch','create','update','delete','alarms'],['NSCalendarsFullAccessUsageDescription for read/write','NSCalendarsWriteOnlyAccessUsageDescription for write-only'], 'Use system event editing for user-confirmed creation without broad access; use explicit full access only for reading/editing existing events.', ['iOS 17 authorization APIs; legacy keys only for older OS paths. Simulator account data differs from device.','Recurring edits require an explicit span; do not delete silently.'], ['docs/frameworks/services/eventkit.md'],'CalendarService.swift'),
 entry('reminders','Reminders',['EventKit'],['authorize','lists','create','due-date','priority','notes','complete','recurrence'],['NSRemindersFullAccessUsageDescription'], 'Request reminders access separately from calendars; let the user choose a writable list.', ['Verify device accounts, due-date time zones and recurrence. No write-only reminders authorization.'], ['docs/frameworks/services/eventkit.md'],'ReminderService.swift'),
 entry('contacts','Contacts',['Contacts','ContactsUI'],['pick','authorize','fetch','search','create','update','thumbnail'],['NSContactsUsageDescription for direct store access only'], 'Prefer CNContactPickerViewController for user-selected contacts. Direct store access must respect limited authorization.', ['Limited access does not imply an empty address book. Do not escalate to full access automatically.','Test limited contacts on an iOS 18+ device.'], ['docs/frameworks/services/contacts.md'],'ContactsService.swift'),
 entry('photos','Photos',['PhotosUI','Photos'],['pick-multiple','filter','load-transferable','save-image','save-video'],['NSPhotoLibraryAddUsageDescription for add-only','NSPhotoLibraryUsageDescription for read/write'], 'Use PhotosPicker for import without broad permission. Request add-only access only when saving.', ['Cloud-backed selections can fail or be cancelled; test offline and large media.','Limited library access is a valid read/write authorization state.'], ['docs/frameworks/photosui.md'],'PhotoLibraryService.swift'),
 entry('camera','Camera',['AVFoundation','UIKit'],['authorize','capture-photo','switch-camera','video-guidance','barcode-guidance'],['NSCameraUsageDescription','NSMicrophoneUsageDescription only for audio recording'], 'Use a presented capture controller for still photos; use AVFoundation for custom video pipelines and VisionKit/metadata output for scanning.', ['Camera availability must be checked at runtime. Simulator cannot verify hardware capture.','Video and barcode support are guidance routes, not generated custom capture pipelines.'], ['docs/frameworks/avfoundation.md','docs/frameworks/visionkit.md'],'CameraService.swift'),
 entry('maps','Maps',['MapKit','CoreLocation'],['map','annotations','search','directions','open-maps','current-location-guidance'],['NSLocationWhenInUseUsageDescription only when accessing device location'], 'MapKit coordinates, search and opening Maps do not require device-location access. Keep location authorization separate.', ['Search/directions require network; Simulator coordinates do not prove device accuracy.','Maps routing UI remains system-controlled.'], ['docs/frameworks/mapkit.md','docs/frameworks/core-location.md'],'MapsService.swift'),
 entry('files','Files',['SwiftUI','UniformTypeIdentifiers'],['import','export','security-scope','pdf'],[], 'Use fileImporter/fileExporter and FileDocument; balance security-scoped access with defer.', ['Test real document providers, cancellation and unavailable files on device.','Provider access is user-mediated, not unrestricted filesystem access.'], ['docs/frameworks/foundation.md'],'DocumentService.swift'),
 entry('sharing','Share Sheet',['SwiftUI','UIKit'],['text','url','image','pdf','file'],[], 'Use ShareLink for Transferable values or UIActivityViewController for mixed items. AirDrop is a system destination.', ['User chooses the destination and confirms. There is no public direct AirDrop-send API.','Available destinations vary by device, installed apps and restrictions.'], ['docs/frameworks/extended-apple-frameworks.md'],'ShareSheet.swift'),
 entry('shortcuts','Siri and Shortcuts',['AppIntents'],['intent','parameters','app-shortcuts','entity-guidance','deep-link-guidance'],[], 'Expose a real app action through AppIntent; use AppEntity/EntityQuery for app-owned data and reuse the App Intents reviewer.', ['A generic scaffold cannot infer your entity store or app navigation.','Device testing is needed for Siri discovery; an AppIntent does not grant data access or require the legacy Siri entitlement.'], ['docs/frameworks/app-intents.md','docs/frameworks/app-intents-intelligence.md'],'IntegrationIntent.swift'),
 entry('notifications','Notifications',['UserNotifications'],['authorize','status','schedule','categories','actions','deep-link'],[], 'Request authorization in context and schedule local notifications; handle responses through a retained delegate.', ['Remote push additionally needs aps-environment, provisioning and a provider; local notifications do not.','Test foreground/background actions and denied permissions on device. Delivery timing is controlled by iOS.'], ['docs/frameworks/usernotifications.md'],'NotificationService.swift'),
];
export function getIntegration(id: string): Integration {
  const result = integrations.find(i => i.id === id);
  if (!result) throw new Error(`Unsupported integration: ${id}. Use list_system_integrations.`);
  return result;
}
