import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,mkdir,rm,readdir} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {generateColorSystem,FAMILIES,STRATEGIES,TOKENS,extractSeed} from '../dist/colors/generate.js';
import {contrast,toLCH,fromLCH,scale} from '../dist/colors/math.js';
import {reviewColorSystem} from '../dist/colors/review.js';
test('WCAG known endpoints and non-rounded boundary',()=>{assert.equal(contrast('#000000','#FFFFFF'),21);assert.equal(contrast('#FFFFFF','#FFFFFF'),1);assert.ok(contrast('#777777','#FFFFFF')<4.5);assert.throws(()=>contrast('#fff','#000000'));});
test('OKLCH round trip and hue preserving gamut mapping',()=>{for(const h of ['#FF0000','#0055AA','#ABCDEF','#000000','#FFFFFF'])assert.equal(fromLCH(...toLCH(h)),h);assert.match(fromLCH(.6,.5,140),/^#[A-F0-9]{6}$/);});
test('all families have complete independent appearance tokens and passing measured pairs',()=>{
 for(const family of FAMILIES){const p=generateColorSystem({family});for(const a of ['light','dark','highContrastLight','highContrastDark']){assert.deepEqual(Object.keys(p[a]).sort(),[...TOKENS].sort());assert.equal(new Set(TOKENS).size,35);for(const c of Object.values(p[a]))assert.match(c,/^#[A-F0-9]{6}$/);for(const pair of p.contrast[a])assert.notEqual(pair.status,'fail',`${family} ${a} ${JSON.stringify(pair)}`);}assert.notDeepEqual(p.light,p.dark);}
});
test('stable derivation, seed priority and all harmonies',()=>{const input={description:'Minimal finance app for young professionals',mood:['calm','trustworthy','premium'],primaryColor:'#145AC8'};assert.deepEqual(generateColorSystem(input),generateColorSystem(input));assert.equal(generateColorSystem(input).seed,'#145AC8');for(const strategy of STRATEGIES)assert.equal(generateColorSystem({strategy}).strategy,strategy);});
test('tonal scales are perceptually ordered, not RGB multiplication',()=>{for(const seed of ['#0011FF','#FF0000','#00FF00','#888888']){const tones=Object.values(scale(seed)).map(c=>toLCH(c)[0]);for(let i=1;i<tones.length;i++)assert.ok(tones[i]<tones[i-1]);}});
test('OLED and high contrast remain distinct from light',()=>{const p=generateColorSystem({appearance:'oled',accessibility:'high',primaryColor:'#FFFF00'});assert.equal(p.dark.background,'#000000');assert.notEqual(p.light.background,'#000000');for(const rows of Object.values(p.contrast))assert.ok(rows.every(r=>r.status!=='fail'));assert.equal(p.contrast.light.find(r=>r.name==='disabled control').required,null);});
test('image samples reject noise and never claim official branding',()=>{const e=extractSeed([{color:'#FFFFFF',weight:100},{color:'#0022CC',weight:20},{color:'#0022CC',weight:5},{color:'#AA0000',weight:2}]);assert.equal(e.seed,'#0022CC');assert.match(e.note,/not an official/);assert.equal(generateColorSystem({imageSamples:[{color:'#0022CC'}]}).seed,'#0022CC');});
test('existing inputs and bounded invalid input',()=>{assert.equal(generateColorSystem({existingTokens:{primary:'#123456'}}).seed,'#123456');assert.equal(generateColorSystem({brandColors:['#654321']}).seed,'#654321');assert.throws(()=>generateColorSystem({primaryColor:'#GGGGGG'}));assert.throws(()=>generateColorSystem({family:'Made up'}));assert.throws(()=>generateColorSystem({description:'a'.repeat(2001)}));});
test('asset export matches established CLI format and gradients are explicitly sampled',()=>{const p=generateColorSystem({strategy:'restrained gradient'});assert.equal(p.assetTokens.version,1);assert.equal(Object.keys(p.assetTokens.colors).length,36);assert.equal(p.assetTokens.colors.Primary.dark,p.dark.primary);assert.equal(Object.keys(p.assetTokens.colors.Primary).length,4);assert.match(p.implementation.swiftUI,/Color\("Primary"\)/);assert.equal(p.gradients.light.stops.length,5);assert.match(p.gradients.light.verification,/Stop samples/);});
async function fixture(fn){const root=await mkdtemp(join(tmpdir(),'color-review-'));try{await fn(root);}finally{await rm(root,{recursive:true,force:true});}}
async function asset(root,name,light,dark){const p=join(root,'Assets.xcassets',name+'.colorset');await mkdir(p,{recursive:true});const entry=(c,d)=>({idiom:'universal',...(d?{appearances:[{appearance:'luminosity',value:'dark'}]}:{}),color:{'color-space':'srgb',components:{red:(parseInt(c.slice(1,3),16)/255).toString(),green:(parseInt(c.slice(3,5),16)/255).toString(),blue:(parseInt(c.slice(5,7),16)/255).toString(),alpha:'1'}}});await writeFile(join(p,'Contents.json'),JSON.stringify({colors:[entry(light,false),...(dark?[entry(dark,true)]:[])]}));}
test('good semantic and valid custom branding produce no concerns',()=>fixture(async root=>{await asset(root,'TextPrimary','#111111','#EEEEEE');await asset(root,'Background','#FFFFFF','#111111');await writeFile(join(root,'View.swift'),'import SwiftUI\nText("Hi").foregroundStyle(Color("TextPrimary")).background(Color("Background"))');const r=await reviewColorSystem(root);assert.equal(r.concerns.length,0);assert.equal(r.lightDarkCoverage.length,2);}));
test('missing dark coverage is advisory not a custom-brand error',()=>fixture(async root=>{await asset(root,'Brand','#145AC8');const r=await reviewColorSystem(root);assert.equal(r.concerns[0].rule,'color-dark-coverage');assert.equal(r.concerns[0].severity,'advisory');}));
test('poor explicit text contrast has line evidence',()=>fixture(async root=>{await asset(root,'TextPrimary','#AAAAAA','#AAAAAA');await asset(root,'Background','#FFFFFF','#BBBBBB');await writeFile(join(root,'View.swift'),'import SwiftUI\nText("Hi").foregroundStyle(Color("TextPrimary")).background(Color("Background"))');const r=await reviewColorSystem(root);assert.equal(r.concerns.filter(c=>c.rule==='color-text-contrast').length,2);assert.equal(r.concerns[0].line,2);}));
test('hardcoded sprawl and duplicates are evidence, not blanket errors',()=>fixture(async root=>{await writeFile(join(root,'View.swift'),'import SwiftUI\n'+Array.from({length:9},(_,i)=>`let c${i}=Color(red: ${i/10}, green: 0.2, blue: 0.4)`).join('\n')+'\nlet other=Color(red: 0, green: 0.2, blue: 0.4)');const r=await reviewColorSystem(root);assert.equal(r.concerns[0].rule,'color-literal-sprawl');assert.equal(r.duplicates.length,1);}));
test('system semantics, gradients and commented colors avoid invented contrast',()=>fixture(async root=>{await writeFile(join(root,'View.swift'),'import SwiftUI\nText("Color(red: 1, green: 0, blue: 0)").foregroundStyle(.primary)\n// Color(red: 1, green: 0, blue: 0)\nlet c=Color(uiColor: .systemGroupedBackground)\nlet g=LinearGradient(colors: [.red,.blue], startPoint: .top, endPoint: .bottom)');const r=await reviewColorSystem(root);assert.equal(r.detectedColors.length,0);assert.equal(r.concerns.length,0);assert.match(r.limitations.join(' '),/gradients/);}));
test('read-only review does not alter files',()=>fixture(async root=>{await writeFile(join(root,'View.swift'),'import SwiftUI');const before=await readdir(root);await reviewColorSystem(root);assert.deepEqual(await readdir(root),before);}));
test('three duplicate catalog appearances stay unresolved',()=>fixture(async root=>{await asset(root,'Brand','#112233');const file=join(root,'Assets.xcassets/Brand.colorset/Contents.json');const {readFile}=await import('node:fs/promises');const d=JSON.parse(await readFile(file,'utf8'));d.colors=[d.colors[0],d.colors[0],d.colors[0]];await writeFile(file,JSON.stringify(d));const r=await reviewColorSystem(root);assert.deepEqual(r.lightDarkCoverage[0].variants,{});assert.equal(r.detectedColors.length,0);}));
test('large literal inventories are truncated explicitly',()=>fixture(async root=>{await writeFile(join(root,'View.swift'),'import SwiftUI\n'+Array.from({length:2100},(_,i)=>`let c${i}=Color(red: 0.1, green: 0.2, blue: 0.3)`).join('\n'));const r=await reviewColorSystem(root);assert.equal(r.detectedColors.length,2048);assert.match(r.limitations.join(' '),/truncated/);assert.equal(r.duplicates.length,1);}));
test('local PNG extraction is bounded, opaque-only and read-only',()=>fixture(async root=>{
 const {createRequire}=await import('node:module');const require=createRequire(import.meta.url);const {PNG}=createRequire(require.resolve('@nagarjuna2002/ios-agent/dist/index.js'))('pngjs');
 const {samplePNG}=await import('../dist/colors/image.js');const p=new PNG({width:2,height:1});p.data.set([20,90,200,255,255,0,0,0]);const path=join(root,'logo.png');await writeFile(path,PNG.sync.write(p));assert.deepEqual(await samplePNG(path),[{color:'#145AC8',weight:1}]);
 const bad=PNG.sync.write(p);bad.writeUInt32BE(20000,16);await writeFile(join(root,'huge.png'),bad);await assert.rejects(()=>samplePNG(join(root,'huge.png')),/dimensions/);
 const {symlink}=await import('node:fs/promises');await symlink(path,join(root,'link.png'));await assert.rejects(()=>samplePNG(join(root,'link.png')),/symlink/);
}));
test('unsupported dark color space is unresolved, not a missing-dark finding',()=>fixture(async root=>{await asset(root,'Brand','#112233','#AABBCC');const {readFile}=await import('node:fs/promises');const file=join(root,'Assets.xcassets/Brand.colorset/Contents.json');const data=JSON.parse(await readFile(file,'utf8'));data.colors[1].color['color-space']='display-p3';await writeFile(file,JSON.stringify(data));const r=await reviewColorSystem(root);assert.equal(r.concerns.length,0);assert.match(r.limitations.join(' '),/Unresolved/);}));
test('PNG decoder cannot bypass dimensions with a second header',()=>fixture(async root=>{const {createRequire}=await import('node:module');const require=createRequire(import.meta.url);const {PNG}=createRequire(require.resolve('@nagarjuna2002/ios-agent/dist/index.js'))('pngjs');const {samplePNG}=await import('../dist/colors/image.js');const small=PNG.sync.write(new PNG({width:1,height:1})),large=PNG.sync.write(new PNG({width:1025,height:1}));const file=join(root,'duplicate.png');await writeFile(file,Buffer.concat([small.subarray(0,33),large.subarray(8)]));await assert.rejects(()=>samplePNG(file),/Duplicate PNG header/);}));
