import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,mkdir,rm,readFile} from 'node:fs/promises';
import {join,dirname} from 'node:path';
import {tmpdir} from 'node:os';
import {integrations,getIntegration} from '../dist/integrations/registry.js';
import {permissionEvidence} from '../dist/integrations/permissions.js';
import {inspectIntegrations} from '../dist/integrations/review.js';
import {scaffoldIntegration} from '../dist/integrations/tools.js';
import {analyzeAppStore} from '../dist/analyzers/appstore.js';
async function fixture(files,run){const root=await mkdtemp(join(tmpdir(),'system-integrations-'));try{for(const [p,s]of Object.entries(files)){await mkdir(dirname(join(root,p)),{recursive:true});await writeFile(join(root,p),s);}return await run(root);}finally{await rm(root,{recursive:true,force:true});}}
const plist=body=>`<?xml version="1.0"?><plist version="1.0"><dict>${body}</dict></plist>`;
test('registry is unique and complete, routes exist, iOS 17 templates',async()=>{assert.equal(integrations.length,10);assert.equal(new Set(integrations.map(i=>i.id)).size,10);for(const i of integrations){assert.equal(getIntegration(i.id),i);assert.equal(i.minimumIOS,17);for(const key of ['name','approach','template','appleURL'])assert.ok(i[key]);for(const key of ['frameworks','operations','limitations','verification','guides'])assert.ok(i[key].length);for(const p of i.guides)await readFile(new URL('../../'+p,import.meta.url));}});
for(const i of integrations)test(`preview ${i.id} preserves project files`,()=>fixture({'Keep.swift':'// owned'},async root=>{const r=await scaffoldIntegration(root,i.id);assert.equal(r.written,false);assert.ok(r.files[0].content.includes('import '));assert.ok(!r.files[0].content.includes('TODO'));assert.equal(await readFile(join(root,'Keep.swift'),'utf8'),'// owned');}));
test('invalid integration and requested operation are explicit errors',()=>fixture({},async root=>{assert.throws(()=>getIntegration('../x'));await assert.rejects(scaffoldIntegration(root,'calendar',['silent-delete']));await assert.rejects(scaffoldIntegration(root,'not-supported'));}));
test('missing path never becomes clean report',async()=>{await assert.rejects(inspectIntegrations('/no-such-integration-project'));await assert.rejects(scaffoldIntegration('/no-such-integration-project','maps'));});
const cases=[['requestFullAccessToEvents()', 'NSCalendarsFullAccessUsageDescription'],['requestWriteOnlyAccessToEvents()','NSCalendarsWriteOnlyAccessUsageDescription'],['requestFullAccessToReminders()','NSRemindersFullAccessUsageDescription'],['requestAccess(to: .event)','NSCalendarsUsageDescription'],['requestAccess(to: .reminder)','NSRemindersUsageDescription'],['store.requestAccess(for: .contacts)','NSContactsUsageDescription'],['PHPhotoLibrary.requestAuthorization(for: .addOnly)','NSPhotoLibraryAddUsageDescription'],['PHPhotoLibrary.requestAuthorization(for: .readWrite)','NSPhotoLibraryUsageDescription'],['AVCaptureDevice.requestAccess(for: .video)','NSCameraUsageDescription'],['AVCaptureDevice.requestAccess(for: .audio)','NSMicrophoneUsageDescription'],['manager.requestWhenInUseAuthorization()','NSLocationWhenInUseUsageDescription'],['manager.requestAlwaysAuthorization()','NSLocationAlwaysAndWhenInUseUsageDescription'],['CBCentralManager()','NSBluetoothAlwaysUsageDescription'],['SFSpeechRecognizer.requestAuthorization()','NSSpeechRecognitionUsageDescription'],['import HealthKit\nstore.requestAuthorization(toShare: [steps], read: [heart])','NSHealthShareUsageDescription'],['import HealthKit\nstore.requestAuthorization(toShare: [steps], read: [])','NSHealthUpdateUsageDescription']];
for(const [code,key]of cases)test(`permission evidence and repaired plist: ${key}`,()=>fixture({'App.swift':code,'Info.plist':plist('')},async root=>{assert.ok(permissionEvidence(code).some(e=>e.key===key));let r=await inspectIntegrations(root);assert.ok(r.findings.some(f=>f.rule==='missing-purpose-string'&&f.message.includes(key)));await writeFile(join(root,'Info.plist'),plist(`<key>${key}</key><string>Used when you choose this feature.</string>`));r=await inspectIntegrations(root);assert.ok(!r.findings.some(f=>f.rule==='missing-purpose-string'&&f.message.includes(key)));}));
for(const code of ['import PhotosUI\nPhotosPicker(selection: $item) {}','import MapKit\nMap { Marker("Place", coordinate: place) }','import ContactsUI\nCNContactPickerViewController()','import AVFoundation\nlet player = AVPlayer()','import EventKit','import HealthKit','let text = "AVCaptureDevice.requestAccess(for: .video)"','/* PHPhotoLibrary.requestAuthorization(for: .readWrite) */','// requestFullAccessToEvents()'])test(`no permission false positive: ${code.split('\n')[0]}`,()=>{assert.deepEqual(permissionEvidence(code),[]);assert.ok(!analyzeAppStore({path:'App.swift',content:code},{infoPlist:'',isApp:true,hasPrivacyManifest:true}).some(f=>f.rule==='missing-purpose-string'));});
test('multiple targets and generated settings are unknown, not missing',()=>fixture({'App.swift':'requestFullAccessToEvents()','A/Info.plist':plist(''),'B/Info.plist':plist(''),'App.xcodeproj/project.pbxproj':'{}'},async root=>{const r=await inspectIntegrations(root);assert.equal(r.permissions.status,'unknown');assert.equal(r.findings.length,0);assert.equal((await inspectIntegrations(root,{infoPlist:'A/Info.plist'})).findings[0].rule,'missing-purpose-string');}));
test('empty description fails and malformed plist stays unknown',()=>fixture({'App.swift':'requestFullAccessToEvents()','Info.plist':plist('<key>NSCalendarsFullAccessUsageDescription</key><string> </string>')},async root=>{assert.equal((await inspectIntegrations(root)).permissions.required[0].status,'missing-or-empty');await writeFile(join(root,'Info.plist'),'not a plist');assert.equal((await inspectIntegrations(root)).permissions.status,'unknown');}));
test('outside selected configuration rejected',()=>fixture({},async root=>{await assert.rejects(inspectIntegrations(root,{infoPlist:'/etc/hosts'}));}));
for(const [code,key,value]of [['HKHealthStore()','com.apple.developer.healthkit','<true/>'],['PKPaymentAuthorizationController(paymentRequest: request)','com.apple.developer.in-app-payments','<array><string>merchant.example</string></array>'],['CKContainer.default()','com.apple.developer.icloud-services','<array><string>CloudKit</string></array>'],['app.registerForRemoteNotifications()','aps-environment','<string>development</string>']])test(`capability ${key} distinct from permission`,()=>fixture({'App.swift':code,'App.entitlements':plist('')},async root=>{assert.ok((await inspectIntegrations(root)).findings.some(f=>f.rule==='missing-integration-capability'));await writeFile(join(root,'App.entitlements'),plist(`<key>${key}</key>${value}`));assert.ok(!(await inspectIntegrations(root)).findings.some(f=>f.rule==='missing-integration-capability'));}));
test('local notifications do not imply push entitlement and empty project has no recommendations',()=>fixture({'App.swift':'import UserNotifications\nUNUserNotificationCenter.current()'},async root=>{const r=await inspectIntegrations(root);assert.equal(r.capabilities.required.length,0);assert.deepEqual(r.detected.map(d=>d.id),['notifications']);await writeFile(join(root,'App.swift'),'');assert.equal((await inspectIntegrations(root)).detected.length,0);}));
test('legacy EventKit advisory and App Intents reviewer reused',()=>fixture({'App.swift':'import Intents\nstore.requestAccess(to: .event)'},async root=>{const r=await inspectIntegrations(root);assert.ok(r.findings.some(f=>f.rule==='eventkit-legacy-authorization-review'));assert.ok(r.findings.some(f=>f.rule==='sirikit-migration-review'));}));
test('sharing uses actual system UI, never a direct AirDrop API',()=>fixture({},async root=>{const r=await scaffoldIntegration(root,'sharing');assert.match(r.files[0].content,/UIActivityViewController/);assert.doesNotMatch(r.files[0].content,/AirDrop\s*\(/);}));

test('constructed contacts store does not imply permission',()=>assert.deepEqual(permissionEvidence('import Contacts\nlet store = CNContactStore()'),[]));
test('CloudDocuments is not CloudKit, and invalid merchant entries fail',()=>fixture({'App.swift':'CKContainer.default()\nPKPaymentAuthorizationController(paymentRequest: request)','App.entitlements':plist('<key>com.apple.developer.icloud-services</key><array><string>CloudDocuments</string></array><key>com.apple.developer.in-app-payments</key><array><false/></array>')},async root=>{assert.equal((await inspectIntegrations(root)).capabilities.required.filter(e=>e.status==='missing-or-invalid').length,2);}));

test('local library excludes generated Xcode build evidence', async()=>{const {buildLibrary}=await import('../../scripts/lib/local-library.mjs');assert.ok(!buildLibrary(new URL('../..',import.meta.url).pathname).files.some(f=>f.path.includes('/build/')));});
