import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {reviewLaunchScreens} from '../dist/analyzers/launch-screen.js';
import {project,storyboard,ids,openstep} from './helpers/launch-project.js';
async function fixture(t,options){const root=await fs.mkdtemp(path.join(os.tmpdir(),'launch-review-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const data=await project(root,options);return {root,data};}
const rules=r=>r.findings.map(f=>f.rule);
async function edit(root,from,to){await fs.writeFile(path.join(root,'LaunchScreen.storyboard'),storyboard.replace(from,to));}
async function save(root,data){await fs.writeFile(path.join(root,'App.xcodeproj/project.pbxproj'),openstep(data));}
test('valid storyboard and empty dictionary launch configurations are clean',async t=>{for(const info of [{UILaunchStoryboardName:'LaunchScreen'},{UILaunchScreen:{}}]){const {root}=await fixture(t,{info});assert.deepEqual(rules(await reviewLaunchScreens(root)),[]);}});
test('generated SwiftUI plist configuration is valid',async t=>{const {root}=await fixture(t,{settings:{GENERATE_INFOPLIST_FILE:'YES',INFOPLIST_FILE:'',INFOPLIST_KEY_UILaunchScreen_Generation:'YES'}});assert.deepEqual(rules(await reviewLaunchScreens(root)),[]);});
test('missing configuration only for proven iOS app',async t=>{const {root,data}=await fixture(t,{info:{}});assert.deepEqual(rules(await reviewLaunchScreens(root)),['launch-configuration-missing']);data.objects[ids.target].productType='com.apple.product-type.framework';await save(root,data);assert.deepEqual(rules(await reviewLaunchScreens(root)),[]);});
test('missing storyboard file, stale name and wrong target membership',async t=>{for(const options of [{info:{UILaunchStoryboardName:'Gone'}},{resources:['Assets.xcassets']},{}]){const {root}=await fixture(t,options);if(!Object.keys(options).length)await fs.unlink(path.join(root,'LaunchScreen.storyboard'));assert.deepEqual(rules(await reviewLaunchScreens(root)),['launch-storyboard-missing']);}});
test('non-dictionary and empty storyboard keys are invalid, not guessed missing',async t=>{for(const info of [{UILaunchScreen:'yes'},{UILaunchStoryboardName:''}]){const {root}=await fixture(t,{info});assert.deepEqual(rules(await reviewLaunchScreens(root)),['launch-configuration-type']);}});
test('overlap is advisory but old OS compatibility fallback is not flagged',async t=>{const {root,data}=await fixture(t,{info:{UILaunchScreen:{},UILaunchStoryboardName:'LaunchScreen'}});assert.equal((await reviewLaunchScreens(root)).findings[0].severity,'minor');data.objects[ids.config].buildSettings.IPHONEOS_DEPLOYMENT_TARGET='13.0';await save(root,data);assert.deepEqual(rules(await reviewLaunchScreens(root)),[]);});
for(const [rule,from,to] of [
 ['launch-storyboard-invalid','</document>',''],
 ['launch-initial-controller-missing','initialViewController="launch"','initialViewController="stale"'],
 ['launch-custom-class','<viewController id="launch"','<viewController customClass="AnimatedLaunch" id="launch"'],
 ['launch-code-connection','</viewController>','<connections><action selector="start:" destination="root" id="action"/></connections></viewController>'],
 ['launch-runtime-attribute','</view>','<userDefinedRuntimeAttributes><userDefinedRuntimeAttribute type="boolean" keyPath="hidden"><bool key="value" value="YES"/></userDefinedRuntimeAttribute></userDefinedRuntimeAttributes></view>'],
 ['launch-deprecated-view','</view>','<subviews><webView id="web"/></subviews></view>'],
])test(rule,async t=>{const {root}=await fixture(t);await edit(root,from,to);assert.ok(rules(await reviewLaunchScreens(root)).includes(rule));});
test('dictionary references absent case-sensitive assets',async t=>{const {root}=await fixture(t,{info:{UILaunchScreen:{UIImageName:'Logo',UIColorName:'Background'}}});assert.equal(rules(await reviewLaunchScreens(root)).filter(x=>x==='launch-asset-missing').length,2);});
test('storyboard image and named color references are checked, system colors are not',async t=>{const {root}=await fixture(t);await edit(root,'</view>','<subviews><imageView image="Logo" id="image"/></subviews><color key="tintColor" name="Brand"/><color key="backgroundColor" systemColor="systemBackgroundColor"/></view>');assert.equal(rules(await reviewLaunchScreens(root)).filter(x=>x==='launch-asset-missing').length,2);});
test('image payload missing inside matching imageset',async t=>{const {root}=await fixture(t,{info:{UILaunchScreen:{UIImageName:'Logo'}}});await fs.mkdir(path.join(root,'Assets.xcassets/Logo.imageset'));await fs.writeFile(path.join(root,'Assets.xcassets/Logo.imageset/Contents.json'),JSON.stringify({images:[{filename:'missing.png'}]}));assert.deepEqual(rules(await reviewLaunchScreens(root)),['launch-asset-file-missing']);await fs.writeFile(path.join(root,'Assets.xcassets/Logo.imageset/missing.png'),'fixture');assert.deepEqual(rules(await reviewLaunchScreens(root)),[]);});
test('unresolved xcconfig, macros and non-iOS targets do not produce missing diagnoses',async t=>{for(const kind of ['xcconfig','macro','mac']){const {root,data}=await fixture(t,{info:{UILaunchStoryboardName:'$(LAUNCH)'}});if(kind==='xcconfig')data.objects[ids.config].baseConfigurationReference='external';if(kind==='mac')data.objects[ids.config].buildSettings.SDKROOT='macosx';await save(root,data);const r=await reviewLaunchScreens(root);assert.deepEqual(rules(r),[]);assert.ok(r.coverage.length);}});
test('legacy and multi-launch configurations are explicitly deferred',async t=>{for(const info of [{UILaunchImages:[]},{UILaunchStoryboards:{}},{UILaunchScreens:{}}]){const {root}=await fixture(t,{info});const r=await reviewLaunchScreens(root);assert.deepEqual(rules(r),[]);assert.ok(r.coverage.some(s=>s.includes('not evaluated')));}});
test('synchronized groups and script-generated resources suppress missing references',async t=>{for(const kind of ['sync','script']){const {root,data}=await fixture(t,{info:{UILaunchStoryboardName:'Generated'}});if(kind==='sync')data.objects[ids.target].fileSystemSynchronizedGroups=['sync'];else{data.objects.script={isa:'PBXShellScriptBuildPhase'};data.objects[ids.target].buildPhases.push('script');}await save(root,data);const r=await reviewLaunchScreens(root);assert.deepEqual(rules(r),[]);assert.ok(r.coverage.length);}});
test('ordinary app intro code and an unused storyboard are not launch behavior',async t=>{const {root}=await fixture(t,{info:{UILaunchScreen:{}}});await edit(root,'<viewController id="launch"','<viewController customClass="Intro" id="launch"');await fs.writeFile(path.join(root,'Intro.swift'),'struct AnimatedIntro { func begin() {} }');assert.deepEqual(rules(await reviewLaunchScreens(root)),[]);});
test('dictionary-only launch screen flags a known pre-iOS-14 deployment target',async t=>{const {root}=await fixture(t,{info:{UILaunchScreen:{}},settings:{IPHONEOS_DEPLOYMENT_TARGET:'13.0'}});assert.deepEqual(rules(await reviewLaunchScreens(root)),['launch-dictionary-availability']);});
test('generated build-setting storyboard reference is evaluated',async t=>{const {root}=await fixture(t,{settings:{GENERATE_INFOPLIST_FILE:'YES',INFOPLIST_KEY_UILaunchStoryboardName:'Retired'}});assert.deepEqual(rules(await reviewLaunchScreens(root)),['launch-storyboard-missing']);});
test('system catalog images are not app assets',async t=>{const {root}=await fixture(t);let s=storyboard.replace('</view>','<subviews><imageView image="star" id="image"/></subviews></view>').replace('</document>','<resources><image name="star" catalog="system" width="20" height="20"/></resources></document>');await fs.writeFile(path.join(root,'LaunchScreen.storyboard'),s);assert.deepEqual(rules(await reviewLaunchScreens(root)),[]);});
test('asset namespace and binary plist are supported',async t=>{const {root}=await fixture(t,{info:{UILaunchScreen:{UIImageName:'Brand/Logo'}}});const {plist}=await import('./helpers/launch-project.js');await fs.writeFile(path.join(root,'Info.plist'),plist.buildBinary({UILaunchScreen:{UIImageName:'Brand/Logo'}}));await fs.mkdir(path.join(root,'Assets.xcassets/Brand/Logo.imageset'),{recursive:true});await fs.writeFile(path.join(root,'Assets.xcassets/Brand/Contents.json'),JSON.stringify({properties:{'provides-namespace':true}}));await fs.writeFile(path.join(root,'Assets.xcassets/Brand/Logo.imageset/Contents.json'),JSON.stringify({images:[{filename:'logo.png'}]}));await fs.writeFile(path.join(root,'Assets.xcassets/Brand/Logo.imageset/logo.png'),'fixture');assert.deepEqual(rules(await reviewLaunchScreens(root)),[]);});
test('symlinks suppress negative asset inventory claims',async t=>{const {root}=await fixture(t,{info:{UILaunchScreen:{UIImageName:'External'}}});await fs.symlink('/tmp',path.join(root,'External'));const r=await reviewLaunchScreens(root);assert.deepEqual(rules(r),[]);assert.ok(r.coverage.some(s=>s.includes('Inventory incomplete')));});
test('excluded resource directory is unknown rather than missing',async t=>{const {root,data}=await fixture(t);const ref=data.objects[data.objects[data.objects[ids.resources].files[0]].fileRef];ref.path='Vendor/LaunchScreen.storyboard';await fs.mkdir(path.join(root,'Vendor'));await fs.writeFile(path.join(root,ref.path),storyboard);await save(root,data);const r=await reviewLaunchScreens(root);assert.deepEqual(rules(r),[]);assert.ok(r.coverage.length);});
test('device-qualified dictionary launch is deferred',async t=>{const {root}=await fixture(t,{info:{'UILaunchScreen~ipad':{}}});const r=await reviewLaunchScreens(root);assert.deepEqual(rules(r),[]);assert.ok(r.coverage.some(s=>s.includes('not evaluated')));});
test('copy phases make missing-resource conclusions uncertain',async t=>{const {root,data}=await fixture(t,{info:{UILaunchScreen:{UIImageName:'Copied'}}});data.objects.copy={isa:'PBXCopyFilesBuildPhase',dstSubfolderSpec:'7',files:[]};data.objects[ids.target].buildPhases.push('copy');await save(root,data);const r=await reviewLaunchScreens(root);assert.deepEqual(rules(r),[]);assert.ok(r.coverage.length);});
test('invalid namespace metadata does not become a missing-image finding',async t=>{const {root}=await fixture(t,{info:{UILaunchScreen:{UIImageName:'Brand/Logo'}}});await fs.mkdir(path.join(root,'Assets.xcassets/Brand/Logo.imageset'),{recursive:true});await fs.writeFile(path.join(root,'Assets.xcassets/Brand/Contents.json'),'{');await fs.writeFile(path.join(root,'Assets.xcassets/Brand/Logo.imageset/Contents.json'),'{}');const r=await reviewLaunchScreens(root);assert.deepEqual(rules(r),[]);assert.ok(r.coverage.some(s=>s.includes('namespace')));});
test('excluded directory inside a catalog makes inventory uncertain',async t=>{const {root}=await fixture(t,{info:{UILaunchScreen:{UIImageName:'Logo'}}});await fs.mkdir(path.join(root,'Assets.xcassets/Vendor/Logo.imageset'),{recursive:true});await fs.writeFile(path.join(root,'Assets.xcassets/Vendor/Logo.imageset/Contents.json'),'{}');const r=await reviewLaunchScreens(root);assert.deepEqual(rules(r),[]);assert.ok(r.coverage.length);});
