import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { execFileSync, spawnSync } from 'node:child_process';
import { project, ids, openstep, plist } from './helpers/launch-project.js';
import { analyzeApp, canonical, EvidenceState } from '../dist/release/model.js';
import { prepareRelease, verifyPackage } from '../dist/release/package.js';
const cli = new URL('../dist/unified.js', import.meta.url).pathname;
async function fixture(t, options = {}) { const root = await fs.mkdtemp(path.join(os.tmpdir(), 'release-foundation-')); t.after(() => fs.rm(root, { recursive: true, force: true })); const data = await project(root, options); data.objects[ids.config].name = 'Release'; data.objects[ids.projectConfig].name = 'Release'; await save(root, data); return { root, data }; }
async function save(root, data) { await fs.writeFile(path.join(root, 'App.xcodeproj/project.pbxproj'), openstep(data)); }
const c = (r, id) => r.model.claims.find(x => x.id === id);
async function source(root, text) { await fs.writeFile(path.join(root, 'App.swift'), text); }
function addSource(data, name, id = 'extra') { data.objects[id] = { isa: 'PBXFileReference', sourceTree: 'SOURCE_ROOT', path: name }; data.objects[id + 'build'] = { isa: 'PBXBuildFile', fileRef: id }; data.objects[ids.sources].files.push(id + 'build'); }
test('SwiftUI identity and screen candidates retain evidence and unknown runtime', async (t) => { const { root } = await fixture(t); await source(root, 'import SwiftUI\nstruct Home: View { var body: some View { NavigationStack { Text("Hi") } } }'); const r = await analyzeApp({ root }); assert.equal(r.model.status, 'ANALYZED_WITH_LIMITATIONS'); assert.equal(c(r, 'bundleIdentifier').value, 'org.example.LaunchFixture'); assert.equal(c(r, 'framework:SwiftUI').status, 'OBSERVED'); assert.equal(r.model.screens[0].runtime, 'NOT_CHECKED'); assert.equal(c(r, 'navigation:NavigationStack').value, 'syntax-present'); const ev = new Set(r.model.evidence.map(e => e.id)); for (const x of [...r.model.claims, ...r.model.features, ...r.model.screens])
    for (const id of x.evidence)
        assert.ok(ev.has(id)); });
test('UIKit controllers are candidates, not proven reachable screens', async (t) => { const { root } = await fixture(t); await source(root, 'import UIKit\nclass Home: UIViewController {}'); const r = await analyzeApp({ root }); assert.ok(c(r, 'framework:UIKit')); assert.equal(r.model.screens[0].reachable, 'UNKNOWN'); });
test('multiple app targets require explicit selection', async (t) => { const { root, data } = await fixture(t); data.objects.second = { ...data.objects[ids.target], name: 'Other' }; data.objects[ids.project].targets.push('second'); await save(root, data); assert.equal((await analyzeApp({ root })).model.status, 'BLOCKED'); assert.equal((await analyzeApp({ root, target: 'Other' })).model.selection.target, 'Other'); });
test('extension is recorded separately and its source does not become app source', async (t) => { const { root, data } = await fixture(t); data.objects.extension = { isa: 'PBXNativeTarget', name: 'Widget', productType: 'com.apple.product-type.app-extension' }; data.objects.dep = { target: 'extension' }; data.objects[ids.target].dependencies = ['dep']; await fs.writeFile(path.join(root, 'Widget.swift'), 'import HealthKit\nlet store=HKHealthStore()'); await save(root, data); const r = await analyzeApp({ root }); assert.deepEqual(c(r, 'extension-targets').value, ['Widget']); assert.ok(!r.model.features.some(f => f.id === 'health')); });
for (const [name, key, code, feature] of [['camera', 'NSCameraUsageDescription', 'AVCaptureSession()', 'camera'], ['photos', 'NSPhotoLibraryUsageDescription', 'PHPhotoLibrary.shared()', 'photos'], ['microphone', 'NSMicrophoneUsageDescription', 'AVAudioRecorder()', 'microphone'], ['location', 'NSLocationWhenInUseUsageDescription', 'CLLocationManager()', 'location'], ['contacts', 'NSContactsUsageDescription', 'CNContactStore()', 'contacts'], ['health', 'NSHealthShareUsageDescription', 'HKHealthStore()', 'health']])
    test(name + ' declaration is evidence, collection remains unknown', async (t) => { const { root } = await fixture(t, { info: { UILaunchScreen: {}, [key]: 'Private purpose text' } }); await source(root, code); const r = await analyzeApp({ root }); assert.ok(c(r, 'permission:' + key)); assert.equal(r.model.features.find(f => f.id === feature).status, 'INFERRED'); assert.equal(c(r, 'server-data-handling').status, 'UNKNOWN'); assert.ok(r.questions.some(q => q.id === 'data-handling')); assert.ok(!canonical(r).includes('Private purpose text')); });
test('package products are target linked; lockfiles do not prove SDK behavior', async (t) => { const { root, data } = await fixture(t); data.objects.sdk = { isa: 'XCSwiftPackageProductDependency', productName: 'Alamofire' }; data.objects[ids.target].packageProductDependencies = ['sdk']; await save(root, data); await fs.writeFile(path.join(root, 'Package.resolved'), '{}'); const r = await analyzeApp({ root }); assert.equal(c(r, 'dependency:Alamofire').status, 'OBSERVED'); assert.equal(c(r, 'external-services').status, 'UNKNOWN'); });
test('analytics indicator stays inferred', async (t) => { const { root } = await fixture(t); await source(root, 'import FirebaseAnalytics\nAnalytics.logEvent("x",parameters:nil)'); const r = await analyzeApp({ root }); assert.equal(r.model.features.find(f => f.id === 'analytics').status, 'INFERRED'); });
test('Sign in with Apple entitlement and code are distinct evidence', async (t) => { const { root } = await fixture(t, { settings: { CODE_SIGN_ENTITLEMENTS: 'App.entitlements' } }); await fs.writeFile(path.join(root, 'App.entitlements'), plist.build({ 'com.apple.developer.applesignin': ['Default'] })); await source(root, 'ASAuthorizationAppleIDProvider()'); const r = await analyzeApp({ root }); assert.ok(c(r, 'entitlement:com.apple.developer.applesignin')); assert.ok(r.model.features.some(f => f.id === 'sign-in-with-apple')); assert.equal(c(r, 'authentication-required').status, 'UNKNOWN'); });
test('StoreKit use does not prove subscriptions offered', async (t) => { const { root } = await fixture(t); await source(root, 'import StoreKit\nlet x=Transaction.currentEntitlements'); const r = await analyzeApp({ root }); assert.equal(c(r, 'subscriptions-offered').status, 'UNKNOWN'); assert.ok(r.questions.some(q => q.id === 'purchases')); });
test('missing Info.plist produces focused blocker without inventing facts', async (t) => { const { root } = await fixture(t); await fs.unlink(path.join(root, 'Info.plist')); const r = await analyzeApp({ root }); assert.equal(c(r, 'info-plist').status, 'UNKNOWN'); assert.ok(r.questions.some(q => q.id === 'identity')); });
test('brief cannot override authentication evidence', async (t) => { const { root } = await fixture(t); await source(root, 'ASAuthorizationController()'); const r = await analyzeApp({ root, prompt: 'For students. No account required.' }); assert.equal(c(r, 'intent:no-account').status, 'CONFLICTING'); assert.ok(r.questions.some(q => q.id === 'auth-conflict')); assert.equal(c(r, 'intent:audience:students').status, 'DEVELOPER_CONFIRMED'); });
test('absence of authentication is unknown', async (t) => { const { root } = await fixture(t); const r = await analyzeApp({ root }); assert.equal(c(r, 'authentication-required').status, 'UNKNOWN'); });
test('launch findings are integrated for the selected target', async (t) => { const { root } = await fixture(t, { info: { UILaunchStoryboardName: 'Missing' } }); const r = await analyzeApp({ root }); assert.ok(c(r, 'launch-finding:launch-storyboard-missing')); });
test('icon configuration and resource evidence remain separate', async (t) => { const { root } = await fixture(t, { settings: { ASSETCATALOG_COMPILER_APPICON_NAME: 'AppIcon' } }); await fs.mkdir(path.join(root, 'Assets.xcassets/AppIcon.appiconset')); await fs.writeFile(path.join(root, 'Assets.xcassets/AppIcon.appiconset/Contents.json'), '{}'); const r = await analyzeApp({ root }); assert.equal(c(r, 'app-icon-resource').value, 'present'); assert.ok(c(r, 'app-icon-name').limitations.length); });
test('only target localization resources are recorded', async (t) => { const { root } = await fixture(t, { resources: ['Localizable.xcstrings'] }); await fs.writeFile(path.join(root, 'Localizable.xcstrings'), '{}'); await fs.writeFile(path.join(root, 'Unused.strings'), '"private"="private";'); const r = await analyzeApp({ root }); assert.equal(r.model.claims.filter(c => c.id.startsWith('localization:')).length, 1); });
test('unselected Swift files cannot add features', async (t) => { const { root } = await fixture(t); await fs.writeFile(path.join(root, 'NotMember.swift'), 'ASAuthorizationController()'); assert.ok(!(await analyzeApp({ root })).model.features.some(f => f.id === 'authentication')); });
test('comments and strings do not become feature evidence', async (t) => { const { root } = await fixture(t); await source(root, '// ASAuthorizationController()\nlet s="HKHealthStore()"\n/* AVCaptureSession() */'); assert.equal((await analyzeApp({ root })).model.features.length, 0); });
test('conditional Swift is explicitly deferred', async (t) => { const { root } = await fixture(t); await source(root, '#if DEBUG\nASAuthorizationController()\n#endif'); const r = await analyzeApp({ root }); assert.equal(r.model.features.length, 0); assert.ok(r.model.coverage.includes('conditional-swift-not-analyzed')); });
test('equivalent analyses and packages are deterministic and reused', async (t) => { const { root } = await fixture(t); const a = await analyzeApp({ root }), b = await analyzeApp({ root }); assert.equal(canonical(a), canonical(b)); const one = await prepareRelease({ root }), two = await prepareRelease({ root }); assert.equal(one.releaseId, two.releaseId); assert.equal(two.reused, true); await verifyPackage(one.path); });
test('source changes invalidate source evidence, preserve resource hash', async (t) => { const { root } = await fixture(t); const a = await prepareRelease({ root }); await source(root, 'import SwiftUI\nstruct Second: View {}'); const b = await prepareRelease({ root }); assert.notEqual(a.releaseId, b.releaseId); assert.notEqual(a.model.sectionHashes.source, b.model.sectionHashes.source); assert.equal(a.model.sectionHashes.resources, b.model.sectionHashes.resources); assert.ok(b.reusedSections.includes('resources')); });
test('asset payload changes invalidate resource evidence', async (t) => { const { root } = await fixture(t); await fs.writeFile(path.join(root, 'Assets.xcassets/payload.png'), 'a'); const a = await analyzeApp({ root }); await fs.writeFile(path.join(root, 'Assets.xcassets/payload.png'), 'b'); const b = await analyzeApp({ root }); assert.notEqual(a.model.sectionHashes.resources, b.model.sectionHashes.resources); assert.equal(a.model.sectionHashes.source, b.model.sectionHashes.source); });
test('dependency lock changes invalidate dependencies', async (t) => { const { root } = await fixture(t); await fs.writeFile(path.join(root, 'Package.resolved'), '{}'); const a = await analyzeApp({ root }); await fs.writeFile(path.join(root, 'Package.resolved'), '{"pins":[]}'); const b = await analyzeApp({ root }); assert.notEqual(a.model.sectionHashes.dependencies, b.model.sectionHashes.dependencies); });
test('tampered package refuses resume', async (t) => { const { root } = await fixture(t); const a = await prepareRelease({ root }); await fs.writeFile(path.join(a.path, 'questions.json'), '[]'); await assert.rejects(prepareRelease({ root }), /evidence changed/); });
test('secrets/source/brief text are not serialized', async (t) => { const { root } = await fixture(t); const token = 'sk-testsecretABCDEFGHIJKLMNOPQRSTUVWXYZ'; await source(root, 'let apiKey="' + token + '"\nURLSession.shared'); await fs.writeFile(path.join(root, 'AuthKey_private.p8'), 'PRIVATE KEY ' + token); await fs.writeFile(path.join(root, 'README.md'), 'password=' + token); const r = await prepareRelease({ root, prompt: 'students password=' + token }); for (const name of await fs.readdir(r.path)) {
    if (name.endsWith('.json'))
        assert.ok(!(await fs.readFile(path.join(r.path, name), 'utf8')).includes(token));
} assert.ok(!canonical(r).includes(token)); });
test('no network or fetch calls are made by analysis or prepare', async (t) => { const { root } = await fixture(t); const original = globalThis.fetch; globalThis.fetch = () => { throw Error('network forbidden'); }; try {
    await analyzeApp({ root });
    await prepareRelease({ root });
}
finally {
    globalThis.fetch = original;
} });
test('JSON CLI works without credentials or AI', async (t) => { const { root } = await fixture(t); const run = spawnSync(process.execPath, [cli, 'apple', 'analyze', '--project', root, '--json'], { encoding: 'utf8', env: { PATH: process.env.PATH, HOME: root } }); assert.equal(run.status, 0, run.stderr); assert.equal(JSON.parse(run.stdout).model.selection.target, 'LaunchFixture'); });
test('ambiguous or non-project folder is blocked, CLI status 2', async (t) => { const root = await fs.mkdtemp(path.join(os.tmpdir(), 'release-empty-')); t.after(() => fs.rm(root, { recursive: true, force: true })); const r = await analyzeApp({ root }); assert.equal(r.model.status, 'BLOCKED'); assert.equal(spawnSync(process.execPath, [cli, 'apple', 'analyze', '--project', root, '--json']).status, 2); });
test('xcconfig and synchronized membership are blocked', async (t) => { for (const mode of ['xcconfig', 'sync']) {
    const { root, data } = await fixture(t);
    if (mode === 'xcconfig')
        data.objects[ids.config].baseConfigurationReference = 'external';
    else
        data.objects[ids.target].fileSystemSynchronizedGroups = ['sync'];
    await save(root, data);
    assert.equal((await analyzeApp({ root })).model.status, 'BLOCKED');
} });
test('symlink package location is rejected', async (t) => { const { root } = await fixture(t); await fs.symlink(os.tmpdir(), path.join(root, '.ios-agent')); await assert.rejects(prepareRelease({ root }), /Unsafe/); });
test('symlinked source is not consumed', async (t) => { const { root } = await fixture(t); await fs.unlink(path.join(root, 'App.swift')); await fs.symlink('/etc/passwd', path.join(root, 'App.swift')); const r = await analyzeApp({ root }); assert.ok(r.model.coverage.includes('source-missing')); });
test('release files are git ignored', async (t) => { const { root } = await fixture(t); execFileSync('git', ['init', '-q'], { cwd: root }); const r = await prepareRelease({ root }); assert.equal(spawnSync('git', ['check-ignore', path.join(r.path, 'app-model.json')], { cwd: root }).status, 0); });
test('simple workspace selects its referenced project', async (t) => { const { root } = await fixture(t); await fs.mkdir(path.join(root, 'App.xcworkspace')); await fs.writeFile(path.join(root, 'App.xcworkspace/contents.xcworkspacedata'), '<Workspace><FileRef location="group:App.xcodeproj"/></Workspace>'); const r = await analyzeApp({ root, workspace: 'App.xcworkspace' }); assert.equal(r.model.selection.workspace, 'App.xcworkspace'); assert.equal(r.model.status, 'ANALYZED_WITH_LIMITATIONS'); });
test('explicit source membership additions change input fingerprint', async (t) => { const { root, data } = await fixture(t); const a = await analyzeApp({ root }); addSource(data, 'Camera.swift'); await fs.writeFile(path.join(root, 'Camera.swift'), 'AVCaptureSession()'); await save(root, data); const b = await analyzeApp({ root }); assert.notEqual(a.sourceFingerprint, b.sourceFingerprint); assert.ok(b.model.features.some(f => f.id === 'camera')); });
test('all six evidence states are representable; invalid states fail', () => { for (const s of ['OBSERVED', 'INFERRED', 'DEVELOPER_CONFIRMED', 'CONFLICTING', 'UNKNOWN', 'NOT_APPLICABLE'])
    assert.equal(EvidenceState.parse(s), s); assert.throws(() => EvidenceState.parse('CERTIFIED')); });
test('URL and raw Swift strings cannot expose fake APIs', async (t) => { const { root } = await fixture(t); await source(root, 'let url="https://example.test"; let fake="AVCaptureSession() import SwiftUI"; let raw=#"ASAuthorizationController()"#'); const r = await analyzeApp({ root }); assert.equal(r.model.features.length, 0); assert.ok(!c(r, 'framework:SwiftUI')); });
test('confirmed no-account brief avoids asking the same question', async (t) => { const { root } = await fixture(t); const r = await analyzeApp({ root, prompt: 'No account required' }); assert.ok(!r.questions.some(q => q.id === 'auth-access')); assert.equal(c(r, 'authentication-required').status, 'UNKNOWN'); });
test('unreadable icon metadata stays unknown', async (t) => { const { root } = await fixture(t, { settings: { ASSETCATALOG_COMPILER_APPICON_NAME: 'AppIcon' } }); await fs.mkdir(path.join(root, 'Assets.xcassets/AppIcon.appiconset')); await fs.writeFile(path.join(root, 'Assets.xcassets/AppIcon.appiconset/Contents.json'), 'x'.repeat(4 * 1024 * 1024 + 1)); assert.equal(c(await analyzeApp({ root }), 'app-icon-resource').status, 'UNKNOWN'); });
test('linked analytics package needs privacy clarification without source calls', async (t) => { const { root, data } = await fixture(t); data.objects.sdk = { productName: 'FirebaseAnalytics' }; data.objects[ids.target].packageProductDependencies = ['sdk']; await save(root, data); assert.ok((await analyzeApp({ root })).questions.some(q => q.id === 'data-handling')); });
test('Info.plist changes invalidate project evidence without losing source evidence', async (t) => { const { root } = await fixture(t); const a = await prepareRelease({ root }); const p = path.join(root, 'Info.plist'); const info = plist.parse(await fs.readFile(p, 'utf8')); info.NSCameraUsageDescription = 'Scan'; await fs.writeFile(p, plist.build(info)); const b = await prepareRelease({ root }); assert.notEqual(a.model.sectionHashes.project, b.model.sectionHashes.project); assert.equal(a.model.sectionHashes.source, b.model.sectionHashes.source); });
test('identical package resume retains package status and semantic hash', async (t) => { const { root } = await fixture(t); const a = await prepareRelease({ root }), b = await prepareRelease({ root }); assert.equal(a.status, b.status); assert.match((await verifyPackage(a.path)).manifest.semanticHash, /^[a-f0-9]{64}$/); });
test('privacy manifests provide declarations, not verified data collection', async (t) => { const { root } = await fixture(t, { resources: ['PrivacyInfo.xcprivacy'] }); await fs.writeFile(path.join(root, 'PrivacyInfo.xcprivacy'), plist.build({ NSPrivacyAccessedAPITypes: [{ NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategoryUserDefaults', NSPrivacyAccessedAPITypeReasons: ['CA92.1'] }] })); const r = await analyzeApp({ root }); assert.ok(c(r, 'required-reason:NSPrivacyAccessedAPICategoryUserDefaults')); assert.ok(r.questions.some(q => q.id === 'data-handling')); });
test('launch findings remain release requirements and package blockers', async (t) => { const { root } = await fixture(t, { info: { UILaunchStoryboardName: 'Gone' } }); const r = await prepareRelease({ root }); assert.ok((await verifyPackage(r.path)).manifest.unresolvedBlockers.includes('launch-finding:launch-storyboard-missing')); });
test('selection outside root is refused', async (t) => { const { root } = await fixture(t); await assert.rejects(analyzeApp({ root, project: '../Outside.xcodeproj' }), /inside project root/); });
test('missing configuration does not silently fall back to Debug', async (t) => { const { root } = await fixture(t); assert.equal((await analyzeApp({ root, configuration: 'Production' })).model.status, 'BLOCKED'); });
test('stale preparation lock is explicit and never silently overridden', async (t) => { const { root } = await fixture(t); await fs.mkdir(path.join(root, '.ios-agent/releases/.prepare-lock'), { recursive: true }); await assert.rejects(prepareRelease({ root }), /locked/); });
test('symlink package artifact is refused', async (t) => { const { root } = await fixture(t); const a = await prepareRelease({ root }); await fs.unlink(path.join(a.path, 'questions.json')); await fs.symlink(path.join(root, 'Info.plist'), path.join(a.path, 'questions.json')); await assert.rejects(prepareRelease({ root }), /Unsafe/); });
test('negated and quoted briefs do not become confirmed facts',async t=>{const {root}=await fixture(t);for(const prompt of ['Login is required. Do not claim no account required.','not for students','"No account required" is false','For students who must sign in. No account required.']){const r=await analyzeApp({root,prompt});assert.ok(!c(r,'intent:no-account'));assert.ok(!c(r,'intent:audience:students'));assert.ok(r.questions.some(q=>q.id==='auth-access'));}});
