import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {PNG} from 'pngjs';
import {project,ids,openstep} from './helpers/launch-project.js';
import {ShipConfig,prepareShip,verifyShip,executeShip,shipCLI} from '../dist/release/ship.js';
const config={schemaVersion:1,project:'App.xcodeproj',scheme:'LaunchFixture',target:'LaunchFixture',bundleId:'org.example.LaunchFixture',teamId:'ABCDE12345',version:'1.0',build:'1',signing:'automatic',metadata:{name:'Fixture',description:'A synthetic app for testing.',supportURL:'https://example.com/support',privacyURL:'https://example.com/privacy',locale:'en-US'},screenshots:[{screens:[{image:'screen.png',headline:'Your daily overview'}]}]};
async function fixture(t){const root=await fs.mkdtemp(join(tmpdir(),'ship-test-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const data=await project(root);data.objects[ids.config].name='Release';data.objects[ids.projectConfig].name='Release';await fs.writeFile(join(root,'App.xcodeproj/project.pbxproj'),openstep(data));const png=new PNG({width:100,height:200});png.data.fill(220);await fs.writeFile(join(root,'screen.png'),PNG.sync.write(png));return root;}
function fakeRunner({failUpload=false,mismatch=false}={}){const calls=[];return {calls,async run(command,args){calls.push({command,args});let stdout='';if(args.includes('-showBuildSettings'))stdout=JSON.stringify([{target:'LaunchFixture',buildSettings:{PRODUCT_BUNDLE_IDENTIFIER:mismatch?'other.app':config.bundleId,MARKETING_VERSION:'1.0',CURRENT_PROJECT_VERSION:'1'}}]);if(args.includes('archive')){const archive=args[args.indexOf('-archivePath')+1];await fs.mkdir(join(archive,'Products/Applications/Fixture.app'),{recursive:true});await fs.writeFile(join(archive,'Info.plist'),'fake');await fs.writeFile(join(archive,'Products/Applications/Fixture.app/Fixture'),'signed fixture');}if(command==='/usr/bin/plutil')stdout=JSON.stringify({ApplicationProperties:{CFBundleIdentifier:config.bundleId,CFBundleShortVersionString:'1.0',CFBundleVersion:'1',Team:config.teamId,ApplicationPath:'Applications/Fixture.app'}});return {exitCode:failUpload&&args.includes('-exportArchive')?1:0,stdout,stderr:'',durationMs:1,timedOut:false};}};}
test('ship config requires explicit identity, signing and supplied screenshots',()=>{assert.equal(ShipConfig.parse(config).allowProvisioningUpdates,false);assert.throws(()=>ShipConfig.parse({...config,teamId:''}));assert.throws(()=>ShipConfig.parse({...config,workspace:'App.xcworkspace'}));assert.throws(()=>ShipConfig.parse({...config,signing:'manual'}));assert.throws(()=>ShipConfig.parse({...config,screenshots:[{}]}));});
test('prepare reuses release analysis and generates sealed screenshot and metadata drafts',async t=>{const root=await fixture(t),plan=await prepareShip(root,config);const saved=await verifyShip(root,plan.id);assert.equal(saved.status,'PREPARED_REQUIRES_REVIEW');assert.ok(saved.files['metadata.json']);assert.ok(Object.keys(saved.files).some(p=>p.endsWith('.png')));assert.equal(JSON.parse(await fs.readFile(join(plan.path,'metadata.json'),'utf8')).privacyAnswers,'NOT_GENERATED');await fs.writeFile(join(plan.path,'metadata.json'),'{}');await assert.rejects(verifyShip(root,plan.id),/artifact changed/);});
test('archive and upload are distinct, identity checked, resumable and processing remains unknown',async t=>{const root=await fixture(t),plan=await prepareShip(root,config),runner=fakeRunner();await assert.rejects(executeShip(root,plan.id,'upload',runner,{}),/Archive missing/);assert.equal(runner.calls.length,0);assert.equal((await executeShip(root,plan.id,'archive',runner,{})).status,'ARCHIVED');assert.ok(!runner.calls.some(c=>c.args.includes('-exportArchive')));const count=runner.calls.length;assert.equal((await executeShip(root,plan.id,'archive',runner,{})).reused,true);assert.equal(runner.calls.length,count);const uploaded=await executeShip(root,plan.id,'upload',runner,{});assert.equal(uploaded.status,'UPLOAD_ACCEPTED_PROCESSING_UNKNOWN');const uploadCount=runner.calls.length;await executeShip(root,plan.id,'upload',runner,{});assert.equal(runner.calls.length,uploadCount);const options=await fs.readFile(join(plan.path,'ExportOptions.plist'),'utf8');assert.match(options,/app-store-connect/);assert.match(options,/manageAppVersionAndBuildNumber/);assert.ok(!runner.calls.some(c=>c.args.includes('-allowProvisioningUpdates')));});
test('ambiguous upload failures never automatically resubmit',async t=>{const root=await fixture(t),plan=await prepareShip(root,config),runner=fakeRunner({failUpload:true});await executeShip(root,plan.id,'archive',runner,{});await assert.rejects(executeShip(root,plan.id,'upload',runner,{}),/upload failed/);const count=runner.calls.length;await assert.rejects(executeShip(root,plan.id,'upload',runner,{}),/uncertain/);assert.equal(runner.calls.length,count);});
test('source edits and wrong Xcode identity prevent signing',async t=>{const root=await fixture(t),plan=await prepareShip(root,config),runner=fakeRunner({mismatch:true});await assert.rejects(executeShip(root,plan.id,'archive',runner,{}),/differ/);assert.ok(!runner.calls.some(c=>c.args.includes('archive')));await fs.appendFile(join(root,'App.swift'),'\n// edited');await assert.rejects(verifyShip(root,plan.id),/Project changed/);});
test('CLI refuses combined external actions and missing approval',async()=>{await assert.rejects(shipCLI(['--project','/tmp','--archive','--upload']),/separate/);await assert.rejects(shipCLI(['--project','/tmp','--upload']),/approve/);await assert.rejects(shipCLI(['--project','/tmp','--unknown']),/Invalid/);});

test('identical preparation reuses the approval ID and review document is sealed',async t=>{const root=await fixture(t),first=await prepareShip(root,config),second=await prepareShip(root,config);assert.equal(first.id,second.id);assert.equal(second.reused,true);await fs.appendFile(join(first.path,'SHIP_PLAN.md'),'\nChanged team');await assert.rejects(verifyShip(root,first.id),/review document changed/);});
test('manual profiles must match resolved target settings before archive',async t=>{const root=await fixture(t),plan=await prepareShip(root,{...config,signing:'manual',provisioningProfiles:{[config.bundleId]:'Distribution profile'}}),runner=fakeRunner();await assert.rejects(executeShip(root,plan.id,'archive',runner,{}),/manual team\/profile/);assert.ok(!runner.calls.some(c=>c.args.includes('archive')));});
test('provisioning and authentication are explicit, private logs remain local',async t=>{const root=await fixture(t),plan=await prepareShip(root,{...config,allowProvisioningUpdates:true}),runner=fakeRunner();await assert.rejects(executeShip(root,plan.id,'archive',runner,{ASC_KEY_ID:'incomplete'}),/all three/);await executeShip(root,plan.id,'archive',runner,{ASC_KEY_ID:'KEY1234567',ASC_KEY_PATH:'/private/key.p8',ASC_ISSUER_ID:'issuer'});const archive=runner.calls.find(c=>c.args.includes('archive'));assert.ok(archive.args.includes('-allowProvisioningUpdates'));assert.ok(archive.args.includes('-authenticationKeyPath'));assert.equal((await fs.stat(join(plan.path,'archive.log'))).mode&0o777,0o600);});
test('a different plan cannot reupload the same bundle/version/build',async t=>{const root=await fixture(t),first=await prepareShip(root,config),runner=fakeRunner();await executeShip(root,first.id,'archive',runner,{});await executeShip(root,first.id,'upload',runner,{});const second=await prepareShip(root,{...config,metadata:{...config.metadata,description:'Updated copy only.'}});await executeShip(root,second.id,'archive',runner,{});const before=runner.calls.length;await assert.rejects(executeShip(root,second.id,'upload',runner,{}),/already has an upload/);assert.equal(runner.calls.length,before);});

test('manual app and extension mappings archive and export without changing build numbers',async t=>{
 const root=await fixture(t);const profiles={[config.bundleId]:'App Distribution','org.example.widget':'Widget Distribution'};
 const plan=await prepareShip(root,{...config,signing:'manual',provisioningProfiles:profiles});const inner=fakeRunner();
 const runner={async run(command,args,opts){const result=await inner.run(command,args,opts);if(args.includes('-showBuildSettings')){const rows=JSON.parse(result.stdout);Object.assign(rows[0].buildSettings,{CODE_SIGN_STYLE:'Manual',DEVELOPMENT_TEAM:config.teamId,PROVISIONING_PROFILE_SPECIFIER:profiles[config.bundleId]});rows.push({target:'Widget',buildSettings:{PRODUCT_TYPE:'com.apple.product-type.app-extension',PRODUCT_BUNDLE_IDENTIFIER:'org.example.widget',CODE_SIGN_STYLE:'Manual',DEVELOPMENT_TEAM:config.teamId,PROVISIONING_PROFILE_SPECIFIER:profiles['org.example.widget']}});result.stdout=JSON.stringify(rows);}return result;}};
 assert.equal((await executeShip(root,plan.id,'archive',runner,{})).status,'ARCHIVED');await executeShip(root,plan.id,'upload',runner,{});
 const xml=await fs.readFile(join(plan.path,'ExportOptions.plist'),'utf8');assert.match(xml,/Widget Distribution/);assert.match(xml,/App Distribution/);
});
test('archive tampering prevents any upload process',async t=>{const root=await fixture(t),plan=await prepareShip(root,config),runner=fakeRunner();await executeShip(root,plan.id,'archive',runner,{});await fs.appendFile(join(plan.path,'App.xcarchive/Products/Applications/Fixture.app/Fixture'),'tampered');const before=runner.calls.length;await assert.rejects(executeShip(root,plan.id,'upload',runner,{}),/Archive missing or changed/);assert.equal(runner.calls.length,before);});
