import test from 'node:test';import assert from 'node:assert/strict';
import {category,documentationTool,inspectClient,withBridge} from '../dist/apple-docs/registry.js';
import {XcodeBackend} from '../dist/apple-docs/bridge.js';
const tool={name:'FutureAppleDocsSearch',description:'Search Apple documentation',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query']}};
function fake(overrides={}){return {connect:async()=>{},close:async()=>{},listTools:async()=>({tools:[tool]}),getServerCapabilities:()=>({}),getServerVersion:()=>({name:'Xcode',version:'synthetic'}),callTool:async()=>({structuredContent:{documents:[{title:'Symbol',uri:'https://developer.apple.com/documentation/test',contents:'Synthetic evidence',kind:'symbol',score:1}]}}),...overrides};}
test('unknown future tools remain in registry',async()=>{const r=await inspectClient(fake({listTools:async()=>({tools:[tool,{name:'NewFutureTool',inputSchema:{type:'object'}}]})}));assert.equal(r.tools[1].category,'unknown');assert.equal(r.documentationTool,tool.name)});
test('discovery respects schema instead of assuming tool name',()=>{assert.equal(documentationTool([tool]).name,tool.name);assert.equal(documentationTool([{...tool,inputSchema:{type:'object',properties:{query:{type:'number'}}}}]),undefined);assert.equal(documentationTool([{...tool,inputSchema:{...tool.inputSchema,required:['query','project']}}]),undefined);assert.equal(category({name:'BuildProject'}),'build')});
test('resources/prompts discovered only when advertised',async()=>{const r=await inspectClient(fake({getServerCapabilities:()=>({resources:{},prompts:{}}),listResources:async()=>({resources:[]}),listPrompts:async()=>({prompts:[]})}));assert.deepEqual(r.resources,{resources:[]});assert.deepEqual(r.prompts,{prompts:[]})});
test('paginated tools discovered',async()=>{const r=await inspectClient(fake({listTools:async p=>p.cursor?{tools:[tool]}:{tools:[],nextCursor:'next'}}));assert.equal(r.tools.length,1)});
test('repeated cursors stop with explicit limit',async()=>{await assert.rejects(inspectClient(fake({listTools:async()=>({tools:[],nextCursor:'same'})})),/catalog_limit/)});
for(const failure of ['handshake','crash','timeout'])test(`${failure} closes bridge and propagates failure`,async()=>{let closed=false;const c=fake({close:async()=>{closed=true},connect:async()=>{if(failure==='handshake')throw Error(failure)}});await assert.rejects(withBridge(undefined,async()=>{throw Error(failure)},()=>c),new RegExp(failure));assert.equal(closed,true)});
test('live-shaped discovered docs tool works without any application fetch',async()=>{const original=global.fetch;global.fetch=()=>{throw Error('network forbidden')};let args;try{const b=new XcodeBackend(undefined,()=>fake({callTool:async p=>{args=p;return {structuredContent:{documents:[{title:'Symbol',uri:'https://developer.apple.com/documentation/test',contents:'Synthetic evidence',kind:'symbol',score:1}]}}}}));assert.equal((await b.search('Symbol'))[0].title,'Symbol');assert.equal(args.name,tool.name);assert.deepEqual(args.arguments,{query:'Symbol'})}finally{global.fetch=original}});
test('missing documentation capability fails explicitly',async()=>{await assert.rejects(new XcodeBackend(undefined,()=>fake({listTools:async()=>({tools:[]})})).search('x'),/unavailable/)});
test('denial and malformed documents are not treated as evidence',async()=>{await assert.rejects(new XcodeBackend(undefined,()=>fake({callTool:async()=>({isError:true})})).search('x'),/denied/);await assert.rejects(new XcodeBackend(undefined,()=>fake({callTool:async()=>({content:[{type:'text',text:'not json'}]})})).search('x'),/malformed/)});
