import { promises as fs } from 'node:fs';
import path from 'node:path';
import { randomBytes, timingSafeEqual } from 'node:crypto';
const identifier = s => typeof s==='string' && /^[a-zA-Z0-9-]{1,80}$/.test(s);
export class LocalBackend {
  constructor(root){this.root=root;this.locks=new Map();}
  dir(id){if(!/^[a-f0-9-]{36}$/.test(id))throw Error('Invalid workspace');return path.join(this.root,id,'backend');}
  async key(id){const dir=this.dir(id);await fs.mkdir(dir,{recursive:true,mode:0o700});const file=path.join(dir,'key');try{return await fs.readFile(file,'utf8');}catch(e){if(e.code!=='ENOENT')throw e;const key=randomBytes(32).toString('hex');try{await fs.writeFile(file,key,{flag:'wx',mode:0o600});return key;}catch(e){if(e.code!=='EEXIST')throw e;return fs.readFile(file,'utf8');}}}
  async environment(id,origin,namespace){if(!identifier(namespace))throw Error('Invalid namespace');return {TEST_RUNNER_STUDIO_BACKEND_URL:origin+'/backend/'+id,TEST_RUNNER_STUDIO_BACKEND_TOKEN:await this.key(id),TEST_RUNNER_STUDIO_BACKEND_NAMESPACE:namespace};}
  async authorized(id,value){const expected=Buffer.from(await this.key(id)),actual=Buffer.from(value??'');return actual.length===expected.length&&timingSafeEqual(actual,expected);}
  async records(id,namespace){if(!identifier(namespace))throw Error('Invalid data namespace');try{return JSON.parse(await fs.readFile(path.join(this.dir(id),namespace+'.json'),'utf8'));}catch(e){if(e.code==='ENOENT')return [];throw e;}}
  async mutate(id,namespace,recordID,fields){
    if(!identifier(namespace)||!identifier(recordID))throw Error('Invalid record identifier');
    if(fields!==null && (!fields||typeof fields!=='object'||Array.isArray(fields)||Object.keys(fields).length>30||Object.entries(fields).some(([k,v])=>!identifier(k)||typeof v!=='string'||v.length>4000)))throw Error('Records require bounded string fields');
    const lock=id+':'+namespace, previous=this.locks.get(lock)??Promise.resolve();
    const work=previous.catch(()=>{}).then(async()=>{const records=await this.records(id,namespace);const next=records.filter(r=>r.id!==recordID);if(fields!==null)next.push({id:recordID,fields,updatedAt:new Date().toISOString()});if(next.length>500||Buffer.byteLength(JSON.stringify(next))>2000000)throw Error('Development dataset limit reached');const dir=this.dir(id);await fs.mkdir(dir,{recursive:true,mode:0o700});const file=path.join(dir,namespace+'.json');await fs.writeFile(file+'.tmp',JSON.stringify(next),{mode:0o600});await fs.rename(file+'.tmp',file);return next.find(r=>r.id===recordID)??null;});
    this.locks.set(lock,work);try{return await work;}finally{if(this.locks.get(lock)===work)this.locks.delete(lock);}
  }
}
export const backendGuide = `This app uses a REAL local REST backend supplied by Studio. Do not substitute UserDefaults or fake responses for backend storage. Read STUDIO_BACKEND_URL, STUDIO_BACKEND_TOKEN and STUDIO_BACKEND_NAMESPACE from ProcessInfo.processInfo.environment at the composition root. No embedded credential, default secret or print of credentials. Missing configuration must show a clear configuration-needed error. Use URLSession async with 15s timeout and validated HTTP status. Requests: GET baseURL/records -> JSON array [{"id":"UUID string","fields":{"title":"example"},"updatedAt":"ISO8601"}]; PUT baseURL/records/<id> with JSON {"fields":{"title":"example"}} -> saved record; DELETE same URL -> HTTP204. Header Authorization: Bearer <token>, X-Workspace: <namespace>, Content-Type: application/json. Fields are string values only (encode numbers/bools as strings); IDs use UUID().uuidString. Store at most500 records; no auth/accounts beyond the scoped development key. Each automated journey has a fresh server namespace, preserved on relaunch. Live preview has its own 'preview' namespace. Treat --studio-reset as local UI reset, do not erase backend records. Show loading, empty and recoverable error states, and refresh from the backend on launch. Inject the backend through a protocol into a MainActor observable model. Use a Codable record struct with id:String,fields:[String:String],updatedAt:String. Prefer explicit CodingKeys if domain models differ. The local server is development-only; production HTTPS/identity/authorization still requires deployment.`;
