// Generated by ios-agent from .ios-agent/spec.json. Capabilities add widgets; do not edit.
import SwiftUI
import WidgetKit

@main
struct FoodDashWidgetsBundle: WidgetBundle {
    var body: some Widget {
        ProgressLiveActivity()
    }
}
